# Generated by Django 3.2.25 on 2024-12-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('air_quality_index', models.IntegerField(default=1, null=True)),
                ('water_quality_index', models.IntegerField(default=1, null=True)),
                ('ph_level', models.FloatField(default=1.0, null=True)),
                ('temperature', models.FloatField(default=1.0, max_length=120, null=True)),
            ],
        ),
    ]
